### ISSUE TITLE
Failed to resolve entry for package "vuetensils"

### ISSUE THREAD

**Issue by bbprojectnet** [Stegosource/vuetensils#150]
Hi,

I have that kind of error during building vite project with vuetensils:

```
[commonjs--resolver] Failed to resolve entry for package "vuetensils". The package may have incorrect main/module/exports specified in its package.json.
```

Version `0.12.6` is the last one, which is works fine, any after that throw "Failed to resolve entry for package" error.

**Comment by AustinGil** [comment]
Interesting. I'll take a look and see what the dealio is. Thank for reporting :)

**Comment by AustinGil** [comment]
Turned out to be a change in how the build artifacts were being generated. Should be fixed with the next release. Thanks again for pointing this out.

I should also mention that although everything is designed to be importable from the main project ("vuetensils"), you can get a slightly smaller footprint if you import everything you need directly from the /src folder. This is how it's done in the documentation `import VAlert from 'vuetensils/src/components/VAlert/VAlert.vue". Much more verbose, but will save some file size.

**Comment by bbprojectnet** [comment]
Works like a charm, thank you :)
