### ISSUE TITLE
VInput multiple on select doesn't work.

### ISSUE THREAD

**Issue by mgambill** [Stegosource/vuetensils#49]
Another scenario vue.js natively supports but not implemented. the *multiple* attribute when added renders correctly but implementation doesn't work.

`<VInput label="Dropdown List (Multi)" type="select" multiple v-model="multiSelectValue" :options="options"/>`

v-model doesn't support arrays

**Comment by Stegosource** [comment]
Thanks. This will be fixed in the next release.

**Comment by Stegosource** [comment]
Small update on this. I tried implementing the logic required to make this work properly. It's close, but it wasn't quite right. The good news is I was able to reproduce the expected behavior on a trimmed down version of the component: https://codesandbox.io/s/sharp-kilby-863y2

Should be a pretty small step to get things hooked up properly in the library.

Thanks again for the bug report. This was super helpful.

**Comment by Stegosource** [comment]
Just published 0.4.5 with this fixed
