### ISSUE TITLE
VToggle isOpen default

### ISSUE THREAD

**Issue by lbineau** [Stegosource/vuetensils#65]
Thank you for this great library with accessibility in mind.

Would it be possible to add a prop to open the VToggle by default?
Right now I don't think it is possible to modify isOpen in the parent component.
https://github.com/Stegosource/vuetensils/blob/master/src/components/VToggle/VToggle.vue#L62

Thank you.

**Comment by Stegosource** [comment]
Oh yeah. I think this was originally in there, but looking at the source, you're right. No way to make it open by default. I'll be adding that soon. Maybe also support for `v-model`. Anything else you think would make this component better?

**Comment by lbineau** [comment]
I was think of it for a use a an accordion but I'm not sure if it fits WAI-ARIA design pattern.
It could the job of another component. What do you think?

**Comment by Stegosource** [comment]
Yeah, I've kind of kicked the can down the road on the accordion. 1) because I personally don't like them, so I dont have much need for it, and 2) because I havent seen a lot of good examples on how to build one with a11y in mind. However, I think there are folks that would like it, and Im sure there is a good a11y solution. It may be a component, or it may be an implementation pattern (I'd like to have a copy/paste cookbook section some day).

For the short term, I don't think I will be building a dedicated accordion component. There's some other more pressing improvements and new features I want to focus on.

**Comment by Stegosource** [comment]
Just fixed this in the latest release.
